### ISSUE TITLE
错别字在tng-technical-manual中

### ISSUE THREAD

**Issue by ECeternalcat** [narwhrl/stcn-docs#1]
具体位于emergency-operations.md文件的第107行 “逃生舱是另一个非常棒的注意” ，其中 “非常棒的主意” 被打成了 “注意 ”

**Comment by narwhrl** [comment]
下次方便的话可以直接创建 _pull request_ 修改~

**Comment by ECeternalcat** [comment]
> 下次方便的话可以直接创建 _pull request_ 修改~

好的，了解
